[package]
name = "railmap"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = { version = "0.8.1", features = ["png", "svg"] }
hyper =   "0.13"
ignore = "0.4.14"
kurbo = "0.5.11"
lru = "0.4.3"
nom = "5.1.1"
nom_locate = "2.0.0"
osmxml = { git = "https://github.com/partim/osmxml.git" }
pango = "0.8"
pangocairo = "0.9"
rstar = "0.7.1"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }

[[bin]]
name = "railmap"
doc = false


[profile.release]
panic = "abort"
