[package]
name = "railmap"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]
edition = "2021"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = { version = "0.17", features = ["png", "svg", "v1_16"] }
clap = { version = "3.1.18", features = ["cargo"] }
hyper = { version = "0.14.19", features = ["server", "http1", "http2", "tcp"] }
ignore = "0.4.14"
kurbo = "0.9.0"
lazy_static = "1.4"
lru = "0.9.0"
nom = "7"
nom_locate = "4"
osmxml = { git = "https://github.com/partim/osmxml.git" }
rstar = "0.10"
serde = { version = "1", features = ["derive"] }
smallvec = { version = "1.8", features = [ "const_generics" ] }
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
toml = "0.7.2"

[features]
default = [ "railwayhistory" ]
railwayhistory = [ ]
overnight = [ ]

[[bin]]
name = "railmap"
doc = false


[profile.release]
panic = "abort"
