name: Packaging

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  package:
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@v8
    with:
      package_build_rules: |
        image:
          - "debian:trixie"
        target: x86_64
      deb_extra_build_packages: libcairo2-dev libpango1.0-dev
      
